sudo: required
dist: trusty
language: nix
script:
  - glibcLocales=$(nix-build --no-out-link "<nixpkgs>" -A glibcLocales)
  - echo $glibcLocales
  - export LOCALE_ARCHIVE_2_27="${glibcLocales}/lib/locale/locale-archive"
  - cd test
  - make
  - cd ..
  - nix-shell --pure make-tar.nix --run 'echo make-tar complete.'
deploy:
  provider: releases
  api_key: $API_KEY
  file:
    - prefetch-github.tar.gz
  skip_cleanup: true
  on:
    tags: true
